site_name: ScholarVista Documentation

nav:
  - Home: index.md
  - Install: install.md
  - Usage: usage.md

theme:
  name: readthedocs

markdown_extensions:
  - admonition # Add admonition support
  - codehilite: # Code highlighting
      guess_lang: false
  - toc: # Table of contents
      permalink: true
