name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 - --version 1.7.1
      - name: Install dependencies
        run: poetry install --with dev
      - name: Lint with Pylint
        run: poetry run pylint scholarvista cli
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 - --version 1.7.1
      - name: Install dependencies
        run: poetry install
      - name: Run tests
        run: poetry run python -m unittest discover tests
